/*
 * This source file was generated by the Gradle 'init' task
 */
package exercise02;

import java.util.Locale;
import java.util.List;

public class App {
  public static void main(String[] args) {
    Locale.setDefault(Locale.US);
    try (Input input = new Input()) {
      List<Animal> pets = input.getPets();
      printPets(pets);

    } catch (Exception e) {
      System.err.println(e.getMessage());
    }
  }

  public static void printPets(List<Animal> pets) {
    for (Animal pet : pets) {
      if (pet instanceof Herbivore) {
        System.out.println(pet.toString());
      }
    }

    for (Animal pet : pets) {
      if (pet instanceof Omnivore) {
        System.out.println(pet.toString());
      }
    }
  }
}