/*
 * This source file was generated by the Gradle 'init' task
 */
package exercise01;

import java.util.Locale;
import java.util.List;

public class App {
  public static void main(String[] args) {
    Locale.setDefault(Locale.US);
    
    try (Input input = new Input()) {
      List<Animal> pets = input.getPets();
      for (Animal pet : pets) {
        System.out.println(pet.toString());
      }

    } catch (Exception e) {
      System.err.println(e.getMessage());
    }
  }
}
