/*
 * This source file was generated by the Gradle 'init' task
 */
package exercise00;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void testAllDogs() {
    String input = "3\ndog\nSnowball\n12\ndog\nSnowball2\n10\ndog\nSnowball3\n9\n";
    String expectedOutput = "Dog name = Snowball, age = 12\nDog name = Snowball2, age = 10\nDog name = Snowball3, age = 9\n";

    ByteArrayInputStream inputStream = new ByteArrayInputStream(input.getBytes());
    System.setIn(inputStream);

    ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    System.setOut(new PrintStream(outputStream));

    App.main(new String[] {});

    assertEquals(expectedOutput, outputStream.toString());
  }

  @Test
  void testMixedPets() {
    String input = "3\ndog\nSnowball\n12\ncat\nKitty\n10\ndog\nBalloon\n9\n";
    String expectedOutput = "Dog name = Snowball, age = 12\nCat name = Kitty, age = 10\nDog name = Balloon, age = 9\n";

    ByteArrayInputStream inputStream = new ByteArrayInputStream(input.getBytes());
    System.setIn(inputStream);

    ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    System.setOut(new PrintStream(outputStream));

    App.main(new String[] {});

    assertEquals(expectedOutput, outputStream.toString());
  }

  @Test
  void testIncorrectInputs() {
    String input = "3\nhamster\ncat\nKitty\n-10\ncat\nFura\n9\n";

    String expectedOutput = "Cat name = Fura, age = 9\n";
    String expectedErrorOutput = "Incorrect input. Unsupported pet type\nIncorrect input. Age <= 0\n";

    ByteArrayInputStream inputStream = new ByteArrayInputStream(input.getBytes());
    System.setIn(inputStream);

    ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    ByteArrayOutputStream errorStream = new ByteArrayOutputStream();
    System.setOut(new PrintStream(outputStream));
    System.setErr(new PrintStream(errorStream));

    App.main(new String[] {});

    assertEquals(expectedOutput, outputStream.toString());
    assertEquals(expectedErrorOutput, errorStream.toString());
  }
}
