/*
 * This source file was generated by the Gradle 'init' task
 */
package exercise03;

import java.util.Locale;
import java.util.List;

public class App {
  public static void main(String[] args) {
    Locale.setDefault(Locale.US);
    try (Input input = new Input()) {
      List<Animal> pets = input.getPets();
      increaseAgeOfOldAnimals(pets);
      printPets(pets);

    } catch (Exception e) {
      System.err.println(e.getMessage());
    }
  }

  public static void printPets(List<Animal> pets) {
    for (Animal pet : pets) {
      System.out.println(pet.toString());
    }
  }

  public static void increaseAgeOfOldAnimals(List<Animal> animals) {
    animals.stream()
        .filter(animal -> animal.getAge() > 10)
        .forEach(animal -> animal.addAge());
  }
}